/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/House.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Tante}
        position={[0.035, 0, 0]}
        scale={[4.923, 0.087, 4.923]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Bois}
        position={[0, 2.301, -4.68]}
        scale={[4.923, 0.087, 10.347]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Bois}
        position={[0, 2.122, -4.646]}
        scale={[4.923, 0.087, 4.356]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Bois}
        position={[-1.327, 1.09, -4.609]}
        scale={[0.117, 1, 0.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Bois}
        position={[1.406, 1.09, -4.609]}
        scale={[0.117, 1, 0.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Bois}
        position={[-2.289, 2.116, -4.652]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.117, 0.666, 0.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Bois}
        position={[1.826, 2.116, -4.652]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.117, 0.666, 0.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Bois}
        position={[2.469, 3.344, -0.093]}
        rotation={[-Math.PI / 2, 0.96, 0]}
        scale={[0.398, 1.97, 0.144]}
      />
      <group position={[-0.914, 1.424, -3.726]} scale={[1.282, 0.113, 0.816]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Bois2}
        />
      </group>
      <group position={[1.032, 0.652, -3.535]} scale={0.062}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_2.geometry}
          material={materials.Bois2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_3.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-3.258, 1.381, -3.635]} scale={[0.656, 0.213, 0.421]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials.Bois2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[2.848, 0.567, -1.94]}
        scale={[1.092, 0.174, 2.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[2.848, 0.543, -1.94]}
        scale={[1.092, 0.194, 2.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[2.836, 1.381, -3.635]}
        scale={[0.656, 0.213, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[2.846, 1.107, -4.406]}
        scale={[1.096, 1, 0.114]}
      />
    </group>
  )
}

useGLTF.preload('/House.glb')

/*
rembrandt

city
*/